ALTER TABLE vendors ADD bio NVARCHAR(1000) NULL;
ALTER TABLE vendors ADD description NVARCHAR(2000) NULL;
ALTER TABLE vendors ADD website_url NVARCHAR(500) NULL;
ALTER TABLE vendors ADD phone NVARCHAR(30) NULL;
